# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20170418_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized', models.BooleanField(default=False)),
                ('handle', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('netid', models.CharField(blank=True, max_length=50)),
                ('modOrNot', models.BooleanField(default=False)),
                ('blockedOrNot', models.BooleanField(default=False)),
                ('classYear', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='helpfulId',
            field=models.ManyToManyField(related_name='_answer_helpfulId_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='inappropriateId',
            field=models.ManyToManyField(related_name='_answer_inappropriateId_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='inappropriateId',
            field=models.ManyToManyField(related_name='_question_inappropriateId_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
