# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170421_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='inappropriateId',
            field=models.ManyToManyField(related_name='flagged_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
