# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170426_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='helpfulId',
            field=models.ManyToManyField(related_name='inappropriate_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='inappropriateId',
            field=models.ManyToManyField(related_name='helpful_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
