# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170427_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='helpfulId',
            field=models.ManyToManyField(related_name='helpful_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='inappropriateId',
            field=models.ManyToManyField(related_name='inappropriate_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
